/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author husai
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        client = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        mpname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mpid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        protab = new javax.swing.JTable();
        b2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        client.setTitle("Client Access");
        client.setMinimumSize(new java.awt.Dimension(660, 440));
        client.setResizable(false);

        jPanel2.setLayout(null);

        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setText("Load");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);
        b1.setBounds(270, 96, 100, 37);

        mpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpnameActionPerformed(evt);
            }
        });
        mpname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpnameKeyPressed(evt);
            }
        });
        jPanel2.add(mpname);
        mpname.setBounds(390, 20, 173, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Coustmer Id");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 107, 17);

        mpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpidKeyPressed(evt);
            }
        });
        jPanel2.add(mpid);
        mpid.setBounds(140, 20, 110, 30);

        protab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BillNo", "Coustmer ID", "Name", "Amount", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(protab);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 161, 630, 200);

        b2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b2.setText("Load");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(270, 100, 100, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Coustmer Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 20, 112, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(489, 105, 67, 25);

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 660, 410);

        javax.swing.GroupLayout clientLayout = new javax.swing.GroupLayout(client.getContentPane());
        client.getContentPane().setLayout(clientLayout);
        clientLayout.setHorizontalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        clientLayout.setVerticalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        client.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setResizable(false);

        jPanel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton4.setText("ShopOwner");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 390, 160, 40);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton5.setText("Client");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(530, 400, 120, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 160, 380, 50);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Please Select One");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 300, 330, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BUISNESS MANAGMENT SYSTEM");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 60, 630, 50);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 690, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login a=new login();
        a.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
client.setVisible(true);        /*client a=new client();
        a.setVisible(true); */


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpnameActionPerformed

    private void mpnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpnameKeyPressed
        b2.setVisible(true);
        b1.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_mpnameKeyPressed

    private void mpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpidKeyPressed
        b1.setVisible(true);
        b2.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_mpidKeyPressed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` WHERE cid=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpid.getText());
            
           
            rs=pst.executeQuery();
           /* if(rs.next()== false)
           {
              JOptionPane.showMessageDialog(this, "Either You entered wrong details Or you ar not present in records please verify once");
           
           }
           else*/
           
            DefaultTableModel tm =(DefaultTableModel)protab.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }
            con.close();
mpid.setText(""); 
      mpname.setText("");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }

            // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed
Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` WHERE cname=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpname.getText());
            
           
            rs=pst.executeQuery();
           /* if(rs.next()== false)
           {
              JOptionPane.showMessageDialog(this, "Either You entered wrong details Or you ar not present in records please verify once");
           
           }
           else*/
           
            DefaultTableModel tm =(DefaultTableModel)protab.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    mpid.setText(""); 
      mpname.setText("");
           
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)protab.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);    }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JFrame client;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mpid;
    private javax.swing.JTextField mpname;
    private javax.swing.JTable protab;
    // End of variables declaration//GEN-END:variables
}
