/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor2;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author husai
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bills = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtpname = new javax.swing.JTextField();
        txtamt = new javax.swing.JTextField();
        txtqty = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        txtpcode = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txttot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        txtpay = new javax.swing.JTextField();
        bill = new javax.swing.JButton();
        pbill = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rj2 = new javax.swing.JRadioButton();
        rj1 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtgst = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        billno = new javax.swing.JLabel();
        clients = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        protab1 = new javax.swing.JTable();
        mpid1 = new javax.swing.JTextField();
        mpname1 = new javax.swing.JTextField();
        mprice2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rj4 = new javax.swing.JRadioButton();
        rj3 = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        viewbill = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        protab2 = new javax.swing.JTable();
        b2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        mpname2 = new javax.swing.JTextField();
        mpid2 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        inventory = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        mpid = new javax.swing.JTextField();
        mpname = new javax.swing.JTextField();
        mprice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        protab = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        date2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        bills.setTitle("BILLING");
        bills.setAutoRequestFocus(false);
        bills.setResizable(false);
        bills.setSize(new java.awt.Dimension(1130, 650));
        bills.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                billsWindowActivated(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "ProuctName", "Quantity", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Code");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(16, 44, 99, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(152, 44, 105, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 40, 65, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 40, 39, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 40, 70, 19);

        txtprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtprice);
        txtprice.setBounds(404, 70, 108, 32);

        txtpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtpname);
        txtpname.setBounds(152, 70, 108, 32);

        txtamt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtamt);
        txtamt.setBounds(550, 70, 108, 32);

        txtqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtqty.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
        txtqty.setName(""); // NOI18N
        txtqty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtqtyStateChanged(evt);
            }
        });
        jPanel1.add(txtqty);
        txtqty.setBounds(310, 70, 60, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 140, 73, 23);

        txtpcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpcodeKeyPressed(evt);
            }
        });
        jPanel1.add(txtpcode);
        txtpcode.setBounds(10, 70, 130, 32);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("Remove");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(543, 140, 100, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Pay");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 90, 28, 19);

        txttot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txttot);
        txttot.setBounds(10, 40, 126, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Total");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 10, 38, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Balance");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 160, 59, 19);

        txtbal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtbal);
        txtbal.setBounds(10, 180, 126, 32);

        txtpay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpayFocusLost(evt);
            }
        });
        txtpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpayKeyPressed(evt);
            }
        });
        jPanel2.add(txtpay);
        txtpay.setBounds(10, 120, 126, 32);

        bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bill.setText("Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel2.add(bill);
        bill.setBounds(340, 30, 89, 25);

        pbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pbill.setText("Print Bill");
        pbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbillActionPerformed(evt);
            }
        });
        jPanel2.add(pbill);
        pbill.setBounds(190, 170, 89, 25);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Type"));

        buttonGroup1.add(rj2);
        rj2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        rj2.setText("Cash");
        rj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rj2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rj1);
        rj1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        rj1.setText("Credit");
        rj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rj2)
                    .addComponent(rj1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(rj2)
                .addContainerGap())
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(180, 10, 130, 135);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(340, 130, 67, 25);

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Hardware Shop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Coustmer Name");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(330, 90, 112, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GST Number");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(710, 90, 88, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("The Hardware Shop");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel12);
        jLabel12.setBounds(350, 20, 240, 30);

        txtcname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnameActionPerformed(evt);
            }
        });
        txtcname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnameKeyPressed(evt);
            }
        });
        jPanel3.add(txtcname);
        txtcname.setBounds(450, 80, 250, 32);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Coustmer ID");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 80, 89, 17);

        txtcid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcidKeyPressed(evt);
            }
        });
        jPanel3.add(txtcid);
        txtcid.setBounds(110, 80, 190, 32);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bill No");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 30, 45, 19);

        txtgst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgstKeyPressed(evt);
            }
        });
        jPanel3.add(txtgst);
        txtgst.setBounds(810, 80, 280, 32);

        date1.setBackground(new java.awt.Color(255, 255, 255));
        date1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(date1);
        date1.setBounds(1000, 10, 120, 30);

        billno.setBackground(new java.awt.Color(255, 255, 255));
        billno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(billno);
        billno.setBounds(70, 20, 120, 30);

        javax.swing.GroupLayout billsLayout = new javax.swing.GroupLayout(bills.getContentPane());
        bills.getContentPane().setLayout(billsLayout);
        billsLayout.setHorizontalGroup(
            billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsLayout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(billsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(billsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        billsLayout.setVerticalGroup(
            billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billsLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(billsLayout.createSequentialGroup()
                        .addGroup(billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        clients.setTitle("MANAGE CLIENTS");
        clients.setMinimumSize(new java.awt.Dimension(670, 453));
        clients.setResizable(false);
        clients.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                clientsWindowActivated(evt);
            }
        });

        jPanel4.setLayout(null);

        protab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "GST NUMBER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        protab1.setOpaque(false);
        jScrollPane4.setViewportView(protab1);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(10, 173, 630, 200);

        mpid1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(mpid1);
        mpid1.setBounds(174, 11, 110, 30);

        mpname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpname1ActionPerformed(evt);
            }
        });
        jPanel4.add(mpname1);
        mpname1.setBounds(424, 11, 173, 30);

        mprice2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mprice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprice2ActionPerformed(evt);
            }
        });
        jPanel4.add(mprice2);
        mprice2.setBounds(221, 55, 227, 30);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(307, 122, 73, 25);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Coustmer Id");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(54, 24, 107, 17);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("GST Number");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(99, 61, 88, 17);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Coustmer Name");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(294, 24, 112, 17);

        jPanel8.setFocusTraversalPolicyProvider(true);
        jPanel8.setOpaque(false);

        buttonGroup2.add(rj4);
        rj4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rj4.setForeground(new java.awt.Color(255, 255, 255));
        rj4.setText("Without GST Number");
        rj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rj4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rj3);
        rj3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rj3.setForeground(new java.awt.Color(255, 255, 255));
        rj3.setText("Has GST Number");
        rj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rj3ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("View Costmers");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rj3)
                    .addComponent(rj4)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(rj4)
                .addGap(18, 18, 18)
                .addComponent(rj3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8);
        jPanel8.setBounds(466, 55, 160, 96);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(65, 122, 67, 25);

        jButton17.setText("HOME");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17);
        jButton17.setBounds(1040, 10, 61, 23);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setText("HOME");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);
        jButton18.setBounds(600, 0, 69, 23);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\husai\\OneDrive\\Desktop\\wall.jpg")); // NOI18N
        jLabel29.setText("jLabel20");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(0, 0, 650, 420);

        javax.swing.GroupLayout clientsLayout = new javax.swing.GroupLayout(clients.getContentPane());
        clients.getContentPane().setLayout(clientsLayout);
        clientsLayout.setHorizontalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        clientsLayout.setVerticalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        viewbill.setTitle("VIEW BILL");
        viewbill.setMinimumSize(new java.awt.Dimension(655, 401));
        viewbill.setResizable(false);

        jPanel5.setLayout(null);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Coustmer Id");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(20, 30, 88, 17);

        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setText("Load");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel5.add(b1);
        b1.setBounds(20, 90, 67, 25);

        protab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BillNo", "Coustmer ID", "Name", "Amount", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(protab2);

        jPanel5.add(jScrollPane5);
        jScrollPane5.setBounds(10, 160, 600, 190);

        b2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b2.setText("Load");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel5.add(b2);
        b2.setBounds(20, 90, 67, 25);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Coustmer Name");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(300, 30, 112, 17);

        mpname2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpname2ActionPerformed(evt);
            }
        });
        mpname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpname2KeyPressed(evt);
            }
        });
        jPanel5.add(mpname2);
        mpname2.setBounds(440, 30, 170, 23);

        mpid2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpid2KeyPressed(evt);
            }
        });
        jPanel5.add(mpid2);
        mpid2.setBounds(120, 30, 160, 23);

        b3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b3.setText("Load All Bills");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel5.add(b3);
        b3.setBounds(210, 90, 117, 25);

        b4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b4.setText("Load Pending Bills");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel5.add(b4);
        b4.setBounds(420, 90, 160, 25);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("Clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13);
        jButton13.setBounds(513, 126, 67, 25);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\husai\\OneDrive\\Desktop\\wall.jpg")); // NOI18N
        jLabel27.setText("jLabel20");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(0, 0, 650, 420);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton19.setText("HOME");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton19);
        jButton19.setBounds(585, 0, 65, 23);

        javax.swing.GroupLayout viewbillLayout = new javax.swing.GroupLayout(viewbill.getContentPane());
        viewbill.getContentPane().setLayout(viewbillLayout);
        viewbillLayout.setHorizontalGroup(
            viewbillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        viewbillLayout.setVerticalGroup(
            viewbillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        inventory.setTitle("INVENTORY");
        inventory.setMinimumSize(new java.awt.Dimension(650, 440));

        jPanel9.setLayout(null);

        mpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpidActionPerformed(evt);
            }
        });
        jPanel9.add(mpid);
        mpid.setBounds(122, 47, 110, 30);

        mpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel9.add(mpname);
        mpname.setBounds(354, 47, 123, 30);

        mprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel9.add(mprice);
        mprice.setBounds(534, 47, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);
        jButton4.setBounds(260, 80, 73, 25);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("View Inventory");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5);
        jButton5.setBounds(230, 120, 140, 25);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Product Id");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(33, 54, 107, 17);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(495, 54, 33, 17);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Product Name");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(242, 54, 99, 17);

        protab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        protab.setOpaque(false);
        jScrollPane3.setViewportView(protab);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(80, 170, 510, 200);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Clear");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton14);
        jButton14.setBounds(550, 120, 67, 25);

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\husai\\OneDrive\\Desktop\\wall.jpg")); // NOI18N
        jLabel30.setText("jLabel20");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(0, 0, 650, 420);

        javax.swing.GroupLayout inventoryLayout = new javax.swing.GroupLayout(inventory.getContentPane());
        inventory.getContentPane().setLayout(inventoryLayout);
        inventoryLayout.setHorizontalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        inventoryLayout.setVerticalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        jLabel24.setText("jLabel24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel7.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HI!!! Welcome Back");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(68, 52, 313, 29);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Inventory");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(10, 120, 170, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Manage Clients");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(10, 220, 170, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Genrate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(210, 120, 170, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Manage Bills");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(210, 220, 170, 40);

        date2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(date2);
        date2.setBounds(271, 7, 110, 27);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\husai\\OneDrive\\Desktop\\wall.jpg")); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(0, 0, 390, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtqtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtqtyStateChanged
        int qty =Integer.parseInt(txtqty.getValue().toString());
        int price = Integer.parseInt(txtprice.getText());
        int tot = qty * price;
        txtamt.setText(String.valueOf(tot));
       
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model =(DefaultTableModel)table1.getModel();
        model.addRow(new Object[]

            {

                txtpcode.getText(),
                txtpname.getText(),
                txtqty.getValue().toString(),
                txtprice.getText(),
                txtamt.getText()

            } );

            int sum =0;
            for (int i=0;i<table1.getRowCount();i++)
            {
                sum = sum + Integer.parseInt(table1.getValueAt(i, 4).toString());

            }
            txttot.setText(Integer.toString(sum));
            txtpcode.setText("");
            txtpname.setText("");
            txtprice.setText("");
            txtamt.setText("");

            txtpcode.requestFocus();
             txtqty.setValue(1);

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
   Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private void txtpcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpcodeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String pcode = txtpcode.getText();

            try{
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");
                String sql="Select * from product where id = ?";
                pst=con.prepareStatement(sql);
                pst.setString(1, pcode);
                rs = pst.executeQuery();

                if(rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");

                }
                else
                {
                    String pname = rs.getString("prodname");
                    String price = rs.getString("price");
                    txtpname.setText(pname.trim());
                    txtprice.setText(price.trim());

                    int a=Integer.parseInt(txtprice.getText());
                    int qty =Integer.parseInt(txtqty.getValue().toString());
                    int b=a*qty;
                    txtamt.setText(""+b);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtpcodeKeyPressed

    private void txtpayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpayFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayFocusGained

    private void txtpayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpayFocusLost
        int pay=0;
        int total =Integer.parseInt(txttot.getText());
        pay = Integer.parseInt(txtpay.getText());

        if (pay ==0 || pay<total)
        {JOptionPane.showMessageDialog(this, "amount paid lesser than bill amount");

            bill.setEnabled(false);}
        else
        {

            bill.setEnabled(true);}// TODO add your handling code here:
    }//GEN-LAST:event_txtpayFocusLost

    private void txtpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayKeyPressed
public void Balance()
 {
 int pay=0;
 int total =Integer.parseInt(txttot.getText());
pay = Integer.parseInt(txtpay.getText());
int bal = pay - total;
txtbal.setText(String.valueOf(bal));
 /*if (pay ==0 || pay<total)
 {JOptionPane.showMessageDialog(this, "amount paid lesser than bill amount");
           }*/
 }
    

  public void Bill()
  {
  
    String total = txttot.getText();
    String pay = txtpay.getText();
    String bal = txtbal.getText();
    DefaultTableModel model = new DefaultTableModel();
model =(DefaultTableModel)table1.getModel();
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "**              POSSBILL                       \n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Bill No"+"\t"+billno.getText()+"\t"+"\t"+"     Date"+date1.getText()+"\n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Name"+"\t"+"\t"+txtcname.getText()+"\t"+"\t"+"\n"+"Coustmer Id"+"\t"+txtcid.getText()+"\n"+"GST NO"+"\t"+txtgst.getText()+"\n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Product"+"\t"+"\t"+"Price"+"\t"+"\t"+"Amount"+"\n");

  for (int i=0;i<model.getRowCount();i++)
  {
    String pname = (String)model.getValueAt(i, 1);
    String price = (String)model.getValueAt(i, 3);
    String amount = (String)model.getValueAt(i, 4);
    txtbill.setText(txtbill.getText()+pname+"\t"+"\t"+price+"\t"+"\t"+amount +"\n");
  
  }
  txtbill.setText(txtbill.getText()+ "\n");
  
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"Subtotal : "+total+"\n");
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"pay : "+pay+"\n");
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"Balance : "  + bal + "\n");
  txtbill.setText(txtbill.getText()+ "***********************************************\n");
  txtbill.setText(txtbill.getText()+ "**              THANK YOU COME AGAIN           \n");
  txtbill.setText(txtbill.getText()+ "***********************************************\n");
  }
  public void Credit()
  {
   String total = txttot.getText();
    String pay = txtpay.getText();
    String bal = txtbal.getText();
    DefaultTableModel model = new DefaultTableModel();
model =(DefaultTableModel)table1.getModel();
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "**              POSSBILL                       \n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Bill No"+"\t"+billno.getText()+"\t"+"\t"+"     Date"+date1.getText()+"\n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Name"+"\t"+"\t"+txtcname.getText()+"\t"+"\t"+"\n"+"Coustmer Id"+"\t"+txtcid.getText()+"\n"+"GST NO"+"\t"+txtgst.getText()+"\n");
txtbill.setText(txtbill.getText()+ "***********************************************\n");
txtbill.setText(txtbill.getText()+ "Product"+"\t"+"\t"+"Price"+"\t"+"\t"+"Amount"+"\n");

  for (int i=0;i<model.getRowCount();i++)
  {
    String pname = (String)model.getValueAt(i, 1);
    String price = (String)model.getValueAt(i, 3);
    String amount = (String)model.getValueAt(i, 4);
    txtbill.setText(txtbill.getText()+pname+"\t"+"\t"+price+"\t"+"\t"+amount +"\n");
  
  }
  txtbill.setText(txtbill.getText()+ "\n");
  
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"Subtotal : "+total+"\n");
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"pay : 0"+"\n");
  txtbill.setText(txtbill.getText()+ "\t"+"\t"+"To Be Paied : "  + bal + "\n");
  txtbill.setText(txtbill.getText()+ "***********************************************\n");
  txtbill.setText(txtbill.getText()+ "**              THANK YOU COME AGAIN           \n");
  txtbill.setText(txtbill.getText()+ "***********************************************\n");
  
  
  
  
  }
    
    
    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed

if(rj1.isSelected())
{
    
 txtbal.setText(txttot.getText());
 pbill.setEnabled(true);
 Credit();
}
    
    
    
 else if(rj2.isSelected())
{
    Balance();
        Bill();

        int pay=0;

        pay = Integer.parseInt(txtbal.getText());

        if (pay ==0 || pay>0)
        {
            pbill.setEnabled(true);

        }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void pbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbillActionPerformed
if(rj1.isSelected())
 {
         int bal = Integer.parseInt(txtbal.getText());
         
         String aa ="Un Paid "+bal;
          try {
            txtbill.print();        // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "INSERT INTO bill VALUES (?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, billno.getText());
            pst.setString(2, txtcid.getText());
            pst.setString(3,(txtcname.getText()));
            pst.setString(4,(txttot.getText()));
            pst.setString(5,(date1.getText()));
            pst.setString(6,aa);

            pst.executeUpdate();

            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }

     }
else if(rj2.isSelected())
    {
        try {
            txtbill.print();        // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "INSERT INTO bill VALUES (?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, billno.getText());
            pst.setString(2, txtcid.getText());
            pst.setString(3,(txtcname.getText()));
            pst.setString(4,(txttot.getText()));
            pst.setString(5,(date1.getText()));
            pst.setString(6,"paid");

            pst.executeUpdate();

            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }}
txtcname.setText("");txtbill.setText(""); 
      txttot.setText("");
            txtbal.setText("");
            txtpay.setText("");
            txtqty.setValue(1);
            txtpcode.setText("");
            txtpname.setText("");
            txtcid.setText("");
            txtprice.setText("");
            txtamt.setText("");
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)table1.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);
}
this.dispose();
    }//GEN-LAST:event_pbillActionPerformed

    private void txtcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnameActionPerformed

    private void txtcnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnameKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String cname = txtcname.getText();

            try{
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");
                String sql="Select * from coustmer where cname = ?";
                pst=con.prepareStatement(sql);
                pst.setString(1, cname);
                rs = pst.executeQuery();
                if(rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "Name Code Not Found");

                }
                else
                {
                    String pname = rs.getString("cid");
                    String price = rs.getString("gst");
                    txtcid.setText(pname.trim());
                    txtgst.setText(price.trim());

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            }

        }          // TODO add your handling code here:
    }//GEN-LAST:event_txtcnameKeyPressed

    private void txtcidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcidKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String cname = txtcid.getText();

            try{
                Class.forName("com.mysql.jdbc.Driver");
                com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");
                String sql="Select * from coustmer where cid = ?";
                pst=con.prepareStatement(sql);
                pst.setString(1, cname);
                rs = pst.executeQuery();
                if(rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "Name Code Not Found");

                }

                else
                {
                    String pname = rs.getString("cname");
                    String price = rs.getString("gst");
                    txtcname.setText(pname.trim());
                    txtgst.setText(price.trim());

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
            }

        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtcidKeyPressed

    private void txtgstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgstKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgstKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
bills.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   inventory.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void billsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_billsWindowActivated
Date date = new Date();
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

date1.setText(df.format(date));
        try{
    Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");
  String sqll="select max(billno),cid from bill ";
           pst=con.prepareStatement(sqll);
         
           rs = pst.executeQuery();
            if(rs.next()== false)
           {
             JOptionPane.showMessageDialog(this, "Product Code Not Found");
           
           }
           else
           {
            String a = rs.getString("max(billno)");
     int  b=Integer.parseInt(a);
     b++;
            billno.setText(""+b);
             
           
           }
         

   
  
  }     catch (ClassNotFoundException ex) {    
            Logger.getLogger(user.class.getName()).log(Level.SEVERE, "naa", ex);
        } catch (SQLException ex) {
            Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
        }
       pbill.setEnabled(false);
                                                   // TODO add your handling code here:
    }//GEN-LAST:event_billsWindowActivated

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
clients.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
viewbill.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` WHERE cid=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpid2.getText());

            rs=pst.executeQuery();
            /* if(rs.next()== false)
            {
                JOptionPane.showMessageDialog(this, "Either You entered wrong details Or you ar not present in records please verify once");

            }
            else*/

            DefaultTableModel tm =(DefaultTableModel)protab2.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` WHERE cname=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpname2.getText());

            rs=pst.executeQuery();
          
              { DefaultTableModel tm =(DefaultTableModel)protab2.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }}
           
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void mpname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpname2ActionPerformed

    private void mpname2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpname2KeyPressed
        b2.setVisible(true);
        b1.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_mpname2KeyPressed

    private void mpid2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpid2KeyPressed
        b1.setVisible(true);
        b2.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_mpid2KeyPressed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
  try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` ";
            pst=con.prepareStatement(sql);
          

            rs=pst.executeQuery();
          
              { DefaultTableModel tm =(DefaultTableModel)protab2.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }}
           
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `bill` where status != ? ";
            pst=con.prepareStatement(sql);
           pst.setString(1, "paid");

            rs=pst.executeQuery();
          
              { DefaultTableModel tm =(DefaultTableModel)protab2.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("billno"),rs.getString("cid"),rs.getString("cname"),rs.getInt("amount"),rs.getString("date"),rs.getString("status")};
                tm.addRow(o);
            }}
           
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void clientsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_clientsWindowActivated
mprice2.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_clientsWindowActivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Date date = new Date();
DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

date2.setText(df.format(date));        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void rj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rj3ActionPerformed
        mprice2.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rj3ActionPerformed

    private void rj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rj4ActionPerformed
mprice2.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rj4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{

            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");
            
            String sql1 = "select * from coustmer";
            pst=con.prepareStatement(sql1);
            rs=pst.executeQuery();
            DefaultTableModel tm =(DefaultTableModel)protab1.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getString("cid"),rs.getString("cname"),rs.getString("gst")};
                tm.addRow(o);
            }
            con.close();

        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, "naa ho paega");

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (rj3.isSelected()){ try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "INSERT INTO coustmer VALUES (?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpid1.getText());
            pst.setString(2, mpname1.getText());
            pst.setString(3,(mprice2.getText()));
            pst.executeUpdate();
            String sql1 = "select * from coustmer";
            pst=con.prepareStatement(sql1);
            rs=pst.executeQuery();
            DefaultTableModel tm =(DefaultTableModel)protab1.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getString("cid"),rs.getString("cname"),rs.getString("gst")};
                tm.addRow(o);
            }
            con.close();
            mpid1.setText(""); 
      mprice2.setText("");
            mpname1.setText("");

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }

        }
        else
        {try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "INSERT INTO coustmer VALUES (?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpid1.getText());
            pst.setString(2, mpname1.getText());
            pst.executeUpdate();
            String sql1 = "select * from coustmer";
            pst=con.prepareStatement(sql1);
            rs=pst.executeQuery();
            DefaultTableModel tm =(DefaultTableModel)protab1.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getString("cid"),rs.getString("cname"),rs.getString("gst")};
                tm.addRow(o);
            }
            con.close();
mpid1.setText(""); 
      mprice2.setText("");
            mpname1.setText("");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void mprice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mprice2ActionPerformed

    private void mpname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpname1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
txtcname.setText("");txtbill.setText(""); 
      txttot.setText("");
            txtbal.setText("");
            txtpay.setText("");
            txtqty.setValue(1);
            txtpcode.setText("");
            txtpname.setText("");
            txtcid.setText("");
            txtprice.setText("");
            txtamt.setText("");
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)table1.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
mpid1.setText(""); 
      mprice2.setText("");
            mpname1.setText("");
           
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)protab1.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
mpid2.setText(""); 
      mpname2.setText("");
           
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)protab2.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 mprice.setText("");     mpid.setText(""); 
      mpname.setText("");
           
 DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)protab.getModel();
 while(model.getRowCount()>0)
{
model.removeRow(0);
}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "SELECT * FROM `product` ";
            pst=con.prepareStatement(sql);
           
            rs=pst.executeQuery();
          
              { DefaultTableModel tm =(DefaultTableModel)protab.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getString("id"),rs.getString("prodname"),rs.getInt("price")};
                tm.addRow(o);
            }}
           
            con.close();

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
{ try{
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/minor", "root","");

            String sql = "INSERT INTO product VALUES (?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, mpid.getText());
            pst.setString(2, mpname.getText());
            pst.setString(3,(mprice.getText()));
            pst.executeUpdate();
            String sql1 = "select * from product";
            pst=con.prepareStatement(sql1);
            rs=pst.executeQuery();
            DefaultTableModel tm =(DefaultTableModel)protab.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getString("id"),rs.getString("prodname"),rs.getString("price")};
                tm.addRow(o);
            }
            con.close();
              mprice.setText("");     mpid.setText(""); 
      mpname.setText("");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "naa ho paega");
        }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpidActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
DefaultTableModel model = new DefaultTableModel();
 model =(DefaultTableModel)table1.getModel();
 int a =model.getRowCount();
 a=a-1;
model.removeRow(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
this.dispose();
        user a=new user();
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
this.dispose();
        user a=new user();
        a.setVisible(true);    }//GEN-LAST:event_jButton19ActionPerformed

    private void rj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rj1ActionPerformed
        bill.setEnabled(true);
        txtpay.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rj1ActionPerformed

    private void rj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rj2ActionPerformed
        txtpay.setEnabled(true);     // TODO add your handling code here:
    }//GEN-LAST:event_rj2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton bill;
    private javax.swing.JLabel billno;
    private javax.swing.JFrame bills;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFrame clients;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JFrame inventory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField mpid;
    private javax.swing.JTextField mpid1;
    private javax.swing.JTextField mpid2;
    private javax.swing.JTextField mpname;
    private javax.swing.JTextField mpname1;
    private javax.swing.JTextField mpname2;
    private javax.swing.JTextField mprice;
    private javax.swing.JTextField mprice2;
    private javax.swing.JButton pbill;
    private javax.swing.JTable protab;
    private javax.swing.JTable protab1;
    private javax.swing.JTable protab2;
    private javax.swing.JRadioButton rj1;
    private javax.swing.JRadioButton rj2;
    private javax.swing.JRadioButton rj3;
    private javax.swing.JRadioButton rj4;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtamt;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtgst;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtpcode;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField txttot;
    private javax.swing.JFrame viewbill;
    // End of variables declaration//GEN-END:variables
}
